// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package shim

import (
	"sync"
)

// Ensure, that PartitionRunnerMock does implement PartitionRunner.
// If this is not the case, regenerate this file with moq.
var _ PartitionRunner = &PartitionRunnerMock{}

// PartitionRunnerMock is a mock implementation of PartitionRunner.
//
// 	func TestSomethingThatUsesPartitionRunner(t *testing.T) {
//
// 		// make and configure a mocked PartitionRunner
// 		mockedPartitionRunner := &PartitionRunnerMock{
// 			StartFunc: func(partition PartitionID, finish func())  {
// 				panic("mock out the Start method")
// 			},
// 			StopFunc: func()  {
// 				panic("mock out the Stop method")
// 			},
// 		}
//
// 		// use mockedPartitionRunner in code that requires PartitionRunner
// 		// and then make assertions.
//
// 	}
type PartitionRunnerMock struct {
	// StartFunc mocks the Start method.
	StartFunc func(partition PartitionID, finish func())

	// StopFunc mocks the Stop method.
	StopFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// Start holds details about calls to the Start method.
		Start []struct {
			// Partition is the partition argument value.
			Partition PartitionID
			// Finish is the finish argument value.
			Finish func()
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
		}
	}
	lockStart sync.RWMutex
	lockStop  sync.RWMutex
}

// Start calls StartFunc.
func (mock *PartitionRunnerMock) Start(partition PartitionID, finish func()) {
	if mock.StartFunc == nil {
		panic("PartitionRunnerMock.StartFunc: method is nil but PartitionRunner.Start was just called")
	}
	callInfo := struct {
		Partition PartitionID
		Finish    func()
	}{
		Partition: partition,
		Finish:    finish,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	mock.StartFunc(partition, finish)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//     len(mockedPartitionRunner.StartCalls())
func (mock *PartitionRunnerMock) StartCalls() []struct {
	Partition PartitionID
	Finish    func()
} {
	var calls []struct {
		Partition PartitionID
		Finish    func()
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *PartitionRunnerMock) Stop() {
	if mock.StopFunc == nil {
		panic("PartitionRunnerMock.StopFunc: method is nil but PartitionRunner.Stop was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	mock.StopFunc()
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//     len(mockedPartitionRunner.StopCalls())
func (mock *PartitionRunnerMock) StopCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}
