// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package shim

import (
	"sync"
)

// Ensure, that PartitionRunnerMock does implement PartitionRunner.
// If this is not the case, regenerate this file with moq.
var _ PartitionRunner = &PartitionRunnerMock{}

// PartitionRunnerMock is a mock implementation of PartitionRunner.
//
// 	func TestSomethingThatUsesPartitionRunner(t *testing.T) {
//
// 		// make and configure a mocked PartitionRunner
// 		mockedPartitionRunner := &PartitionRunnerMock{
// 			StartFunc: func(partition PartitionID, startCompleted func())  {
// 				panic("mock out the Start method")
// 			},
// 			StopFunc: func(partition PartitionID, stopCompleted func())  {
// 				panic("mock out the Stop method")
// 			},
// 		}
//
// 		// use mockedPartitionRunner in code that requires PartitionRunner
// 		// and then make assertions.
//
// 	}
type PartitionRunnerMock struct {
	// StartFunc mocks the Start method.
	StartFunc func(partition PartitionID, startCompleted func())

	// StopFunc mocks the Stop method.
	StopFunc func(partition PartitionID, stopCompleted func())

	// calls tracks calls to the methods.
	calls struct {
		// Start holds details about calls to the Start method.
		Start []struct {
			// Partition is the partition argument value.
			Partition PartitionID
			// StartCompleted is the startCompleted argument value.
			StartCompleted func()
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
			// Partition is the partition argument value.
			Partition PartitionID
			// StopCompleted is the stopCompleted argument value.
			StopCompleted func()
		}
	}
	lockStart sync.RWMutex
	lockStop  sync.RWMutex
}

// Start calls StartFunc.
func (mock *PartitionRunnerMock) Start(partition PartitionID, startCompleted func()) {
	if mock.StartFunc == nil {
		panic("PartitionRunnerMock.StartFunc: method is nil but PartitionRunner.Start was just called")
	}
	callInfo := struct {
		Partition      PartitionID
		StartCompleted func()
	}{
		Partition:      partition,
		StartCompleted: startCompleted,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	mock.StartFunc(partition, startCompleted)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//     len(mockedPartitionRunner.StartCalls())
func (mock *PartitionRunnerMock) StartCalls() []struct {
	Partition      PartitionID
	StartCompleted func()
} {
	var calls []struct {
		Partition      PartitionID
		StartCompleted func()
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *PartitionRunnerMock) Stop(partition PartitionID, stopCompleted func()) {
	if mock.StopFunc == nil {
		panic("PartitionRunnerMock.StopFunc: method is nil but PartitionRunner.Stop was just called")
	}
	callInfo := struct {
		Partition     PartitionID
		StopCompleted func()
	}{
		Partition:     partition,
		StopCompleted: stopCompleted,
	}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	mock.StopFunc(partition, stopCompleted)
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//     len(mockedPartitionRunner.StopCalls())
func (mock *PartitionRunnerMock) StopCalls() []struct {
	Partition     PartitionID
	StopCompleted func()
} {
	var calls []struct {
		Partition     PartitionID
		StopCompleted func()
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}

// Ensure, that NodeDelegateMock does implement NodeDelegate.
// If this is not the case, regenerate this file with moq.
var _ NodeDelegate = &NodeDelegateMock{}

// NodeDelegateMock is a mock implementation of NodeDelegate.
//
// 	func TestSomethingThatUsesNodeDelegate(t *testing.T) {
//
// 		// make and configure a mocked NodeDelegate
// 		mockedNodeDelegate := &NodeDelegateMock{
// 			JoinFunc: func(addrs []string, finish func())  {
// 				panic("mock out the Join method")
// 			},
// 			LeaveFunc: func()  {
// 				panic("mock out the Leave method")
// 			},
// 		}
//
// 		// use mockedNodeDelegate in code that requires NodeDelegate
// 		// and then make assertions.
//
// 	}
type NodeDelegateMock struct {
	// JoinFunc mocks the Join method.
	JoinFunc func(addrs []string, finish func())

	// LeaveFunc mocks the Leave method.
	LeaveFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// Join holds details about calls to the Join method.
		Join []struct {
			// Addrs is the addrs argument value.
			Addrs []string
			// Finish is the finish argument value.
			Finish func()
		}
		// Leave holds details about calls to the Leave method.
		Leave []struct {
		}
	}
	lockJoin  sync.RWMutex
	lockLeave sync.RWMutex
}

// Join calls JoinFunc.
func (mock *NodeDelegateMock) Join(addrs []string, finish func()) {
	if mock.JoinFunc == nil {
		panic("NodeDelegateMock.JoinFunc: method is nil but NodeDelegate.Join was just called")
	}
	callInfo := struct {
		Addrs  []string
		Finish func()
	}{
		Addrs:  addrs,
		Finish: finish,
	}
	mock.lockJoin.Lock()
	mock.calls.Join = append(mock.calls.Join, callInfo)
	mock.lockJoin.Unlock()
	mock.JoinFunc(addrs, finish)
}

// JoinCalls gets all the calls that were made to Join.
// Check the length with:
//     len(mockedNodeDelegate.JoinCalls())
func (mock *NodeDelegateMock) JoinCalls() []struct {
	Addrs  []string
	Finish func()
} {
	var calls []struct {
		Addrs  []string
		Finish func()
	}
	mock.lockJoin.RLock()
	calls = mock.calls.Join
	mock.lockJoin.RUnlock()
	return calls
}

// Leave calls LeaveFunc.
func (mock *NodeDelegateMock) Leave() {
	if mock.LeaveFunc == nil {
		panic("NodeDelegateMock.LeaveFunc: method is nil but NodeDelegate.Leave was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLeave.Lock()
	mock.calls.Leave = append(mock.calls.Leave, callInfo)
	mock.lockLeave.Unlock()
	mock.LeaveFunc()
}

// LeaveCalls gets all the calls that were made to Leave.
// Check the length with:
//     len(mockedNodeDelegate.LeaveCalls())
func (mock *NodeDelegateMock) LeaveCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLeave.RLock()
	calls = mock.calls.Leave
	mock.lockLeave.RUnlock()
	return calls
}
